### ISSUE TITLE
Add a link to your blog post in the README

### ISSUE THREAD

**Issue by skorokithakis** [DaleGia/ESPFlash#1]
This library is exactly what I've been looking for, thanks for writing it! Working with SPIFFS is more cumbersome than I'd like, but your library makes it trivial.

Your blog post contains a bunch of useful examples, could you either link the post, or, better yet, add the examples to the README and examples directory?

Also, isn't this library more of a key-value store than a filesystem? Is there a reason why you went with the FS metaphor?

**Comment by DaleGia** [comment]
Updated the README to include a link to the blog post.  In regard to the metaphor, I'll paste in here the response I gave in the reddit thread just so others can see it.

> I went with the filesystem metaphor as ESPFlash uses SPIFFS (SPI Flash File System) to do the heavy lifting, But I always thought the phrase "storing data in SPIFFS" was a little off. ESPFlash really just acts as a kind of abstraction layer for SPIFFS. The ESP8266 Arduino Documentation describes SPIFFS as a filesystem, and seeing as ESPFlash uses it, I thought the metaphor was appropriate. Your comment is completely valid though! ESPFlash currently doesn't use any of the SPIFFS functionality regarding directories. Although strictly speaking, SPIFFS itself only emulates directories anyway. It indeed behaves how you describe.

Glad the library is useful!
