### ISSUE TITLE
No support for formatting the SPIFFS if it's not been formatted.

### ISSUE THREAD

**Issue by UnexpectedMaker** [DaleGia/ESPFlash#3]
Nice library, thanks for making it!

You need to use
`SPIFFS.begin(true) `
to ensure SPIFFS works on a device that has never had SPIFFS formatted on it before.

Any chance of getting that added please?

**Comment by GoDotMad** [comment]
for me I removed the SPIFFS.begin() function

because otherwise I can't make a global instance of the class

**Comment by DaleGia** [comment]
> Nice library, thanks for making it!
> 
> You need to use
> `SPIFFS.begin(true) `
> to ensure SPIFFS works on a device that has never had SPIFFS formatted on it before.
> 
> Any chance of getting that added please?

Thanks for spotting this @UnexpectedMaker. I'll try and get to this tonight.

**Comment by DaleGia** [comment]
> for me I removed the SPIFFS.begin() function
> 
> because otherwise I can't make a global instance of the class

Could you provide an example of what you mean @GoDotMad?

**Comment by GoDotMad** [comment]
I was using platformio 
and was trying  the millis aray example 
but couldn't compile because  you can't call SPIFFS.begin() outside of a function

**Comment by GoDotMad** [comment]
alsto you  are including the wrong header in the beginning of Espflash.h

instead  of #include <FS.h>
it should be #include  <SPIFFS.h>

**Comment by GoDotMad** [comment]
after I fixed this two  issues I continued using the library and it is working  great

**Comment by DaleGia** [comment]
SPIFFS.begin() has been removed from constructors to allow global usage. Examples updated to show the need to call SPIFFS.begin() before using methods.
