### ISSUE TITLE
Missing the definition of the setElementAt() method

### ISSUE THREAD

**Issue by GoDotMad** [DaleGia/ESPFlash#4]
I was getting linking error for the past two hours 
until I tried to lock why this method giving this much errors

when I found that it has no definition
only the declaration with the explaining comment 

now I'm very sad

**Comment by DaleGia** [comment]
Thanks for spotting this @GoDotMad. 

Ill take a look when I have time and implement the function.

**Comment by DaleGia** [comment]
I have removed the prototype for this function as I don't have a board to test it on even if I wrote the function. If anyone comes up with a function for this please submit a pull request and I will merge.
