### ISSUE TITLE
Crashing when running example code (millisArray)

### ISSUE THREAD

**Issue by damianvisser** [DaleGia/ESPFlash#5]
**Error:**
rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5816
entry 0x400806ac
/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/queue.c:621 (xQueueTakeMutexRecursive)- assert failed!
abort() was called at PC 0x4008805f on core 0

**Code:** 
#include <FS.h> 
#include <SPIFFS.h>
#include "ESPFlash.h"

#define ARRAY_FILEPATH  "/millisArray"

ESPFlash<uint32_t> millisArray(ARRAY_FILEPATH);

void setup() 
{
  Serial.begin(115200);
  Serial.println("Begining millisArray example...");

  for(int ii = 0; ii < 10; ii++)
  {
    millisArray.append(millis());
    for(int jj = 0; jj < millisArray.length(); jj++)
    {
      Serial.printf("%d ", millisArray.getElementAt(jj));
    }
    Serial.println();
  }

  Serial.println("Example finished...");
}

void loop() 
{

}

**Comment by DaleGia** [comment]
Hi @Vissnor,

Seems like this error is triggered by some kind of assertion related to a mutex and FreeRTOS. This example was tested on an ESP8266 without using FreeRTOS, and I cant guarantee this specific example will work as is for other setups. Some tweaking may be needed for it to run on the ESP32 whe using the ESP-IDF.

**Comment by damianvisser** [comment]
Hi @DaleGia 
First off thanks for reacting so soon! 
I have a lolin32 lite which is basically a smaller esp32.
I didn't know your library was only for the ESP8266.

**Comment by DaleGia** [comment]
In theory it could also work for the ESP32, but some work and testing will have to be done to make that happen. I dont have much time to do this myself at the moment. But if you are able to.get it working on the ESP32 please share how you do it!

**Comment by damianvisser** [comment]
To be fair, I just started using the esp and I don't think I'll be able to make a library. However I will upload my code when I have figured out how to write and read array values to a file!

**Comment by damianvisser** [comment]
For anyone with an esp32 or lolin32 (lite), this should work. It should also work with the esp8266!
```
#include "Arduino.h"
#include "MyFileManager.h"
#include "FS.h"
#include "SPIFFS.h"

String fileName = "";

void MyFileManager::init(String _fileName) {
  fileName = _fileName;
  
  #ifdef ARDUINO_ARCH_ESP32
    SPIFFS.begin(true); // enable format if mount fails (only for ESP32)
  #else
    SPIFFS.begin();
  #endif
    delay(100);
  
    Serial.println("SPIFFS Information:");
  #ifdef ARDUINO_ARCH_ESP32
    // different methods of getting information
    Serial.print("Total bytes:    "); Serial.println(SPIFFS.totalBytes());
    Serial.print("Used bytes:     "); Serial.println(SPIFFS.usedBytes());
  #else
    FSInfo fs_info;
    SPIFFS.info(fs_info);
    Serial.print("Total bytes:    "); Serial.println(fs_info.totalBytes);
    Serial.print("Used bytes:     "); Serial.println(fs_info.usedBytes);
    Serial.print("Block size:     "); Serial.println(fs_info.blockSize);
    Serial.print("Page size:      "); Serial.println(fs_info.pageSize);
    Serial.print("Max open files: "); Serial.println(fs_info.maxOpenFiles);
    Serial.print("Max path length:"); Serial.println(fs_info.maxPathLength);
    Serial.println();
  #endif

  if (SPIFFS.exists(fileName)) {
    Serial.println("Found sample file.");
  }
  else { 
    Serial.println("Sample file not found.");
  }
}

boolean MyFileManager::clear() {
  File f = SPIFFS.open(fileName, FILE_WRITE);
  if (!f) {
    Serial.println("Failed to open file for writing");
    return false;
  }
  Serial.println("Opened file for deleting file contents.");

  int bytesWritten = f.print("");
   
  f.close();

  return true;
}

boolean MyFileManager::write(String a) {
  File f = SPIFFS.open(fileName, FILE_APPEND);
  if (!f) {
    Serial.println("Failed to open file for writing");
    return false;
  }
//  Serial.println("Opened file for writing.");

  int bytesWritten = f.print(a);
   
  if (bytesWritten > 0) {
//      Serial.print("Bytes written to file: ");
//      Serial.println(bytesWritten);
  } else {
      Serial.println("File write failed");
      return false;
  }
  f.close();

  return true;
}

String MyFileManager::read() {
  String arrayString = "";
  File f = SPIFFS.open(fileName, FILE_READ);
  if (!f) {
    Serial.println("Failed to open file for reading");
    return "";
  }
  Serial.println("Opened file for reading. File contents:");

  while (f.available()) {
    arrayString += (char)f.read();
  }
  Serial.print(arrayString);
  Serial.println("");
  f.close();

  return arrayString;
}
```

**Comment by damianvisser** [comment]
The reading and writing stays the same so you can just take the examples of that. However the order of the includes is important and the init function is important!

**Comment by DaleGia** [comment]
Thanks for sharing @Vissnor! If I get a chance I will add your example to the repository!
