### ISSUE TITLE
(xQueueTakeMutexRecursive)- assert failed!

### ISSUE THREAD

**Issue by Escape-Kent** [DaleGia/ESPFlash#9]
Struggling to run a simple program on ESP32

```
#include <Arduino.h>
#include <ESPFlash.h>

ESPFlash<uint8_t> colour("/colour");

void setup() {

}

void loop() {

}
```

> rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
> configsip: 0, SPIWP:0xee
> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> mode:DIO, clock div:2
> load:0x3fff0018,len:4
> load:0x3fff001c,len:1044
> load:0x40078000,len:10124
> load:0x40080400,len:5828
> entry 0x400806a8
> /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/queue.c:621 (xQueueTakeMutexRecursive)- assert failed!
> abort() was called at PC 0x40085e03 on core 0
> 
> ELF file SHA256: 0000000000000000
> 
> Backtrace: 0x40084d00:0x3ffe38d0 0x40084f75:0x3ffe38f0 0x40085e03:0x3ffe3910 0x400eb4cc:0x3ffe3930 0x40083789:0x3ffe3950 0x40084334:0x3ffe3970 0x4008456d:0x3ffe39c0 0x400eb139:0x3ffe39f0 0x400eb2ce:0x3ffe3a20 0x400eb31f:0x3ffe3a40 0x400e053e:0x3ffe3a60 0x400e116e:0x3ffe3aa0 0x400d0fbe:0x3ffe3b60 0x400d0f1f:0x3ffe3b90 0x400e790b:0x3ffe3bb0 0x40081b6d:0x3ffe3bd0 0x40081d6d:0x3ffe3c20 0x40079247:0x3ffe3c40 0x400792ad:0x3ffe3c70 0x400792b8:0x3ffe3ca0 0x40079465:0x3ffe3cc0 0x400806da:0x3ffe3df0 0x40007c31:0x3ffe3eb0 0x4000073d:0x3ffe3f20
> 
> Rebooting...

**Comment by DaleGia** [comment]
This relates to an issue where ESPFlash could not be used in a global context as SPIFFS.begin() used to be called in the constructor. This has since been resolve. ESPFlash can now be used in a global context, but SPIFFS.begin() must be called before actually ever using any of the ESPFlash methods. all the examples have been updated to reflect this.
